version: "3.9"
services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: ui
    links:
      - api
    depends_on: 
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment: 
      MONGODB_URL: mongodb://db:27017
    ports:
      - "9000:9000"
    container_name: api
    links: 
      - db
    depends_on: 
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: db
    volumes:
      - ./db/:/data/db